import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { MemoryScope } from "../domain/scope";
import { normalizeScope } from "../domain/scope";
import type { GoodMemoryTracer } from "../observability/tracer";
import type { MarkdownArtifactBundle } from "./markdownArtifacts";
import type { PageArtifactBundle } from "./pageArtifacts";

// Read-only workspace file mirror (ADR-010 §8). One root serves exactly one
// durable scope: after every durable mutation inside that scope the scope's
// export bundle is regenerated under the root. The mirror is a projection: it
// is never read back, it never fails the mutation that scheduled it, and each
// swap is atomic at the directory level (write to a sibling temp dir, two
// renames, remove the old) with the previous tree restored if the swap fails.

export interface FileMirrorConfig {
  root: string;
  // The durable scope this root serves. Mutations outside it are ignored;
  // fields the scope leaves unset (for example agentId) admit any value.
  scope: MemoryScope;
  debounceMs?: number;
  regenerateOn?: "mutation";
}

export interface FileMirrorFsPort {
  mkdir(path: string, options: { recursive: true }): Promise<unknown>;
  rename(from: string, to: string): Promise<void>;
  rm(path: string, options: { force: true; recursive: true }): Promise<void>;
  writeFile(path: string, content: string, encoding: "utf8"): Promise<void>;
}

export interface FileMirrorTimers {
  clearTimeout(handle: unknown): void;
  setTimeout(callback: () => void, delayMs: number): unknown;
}

export interface FileMirrorExport {
  artifacts: MarkdownArtifactBundle;
  pages: PageArtifactBundle;
}

export interface FileMirrorDeps {
  config: FileMirrorConfig;
  exportMemory(input: { includeRuntime: false; scope: MemoryScope }): Promise<FileMirrorExport>;
  fs?: FileMirrorFsPort;
  now?: () => Date;
  onFailure?(error: unknown, scope: MemoryScope): void;
  timers?: FileMirrorTimers;
  tracer?: GoodMemoryTracer;
}

export interface FileMirror {
  readonly root: string;
  flush(): Promise<void>;
  schedule(scope: MemoryScope): void;
}

export const FILE_MIRROR_DEFAULT_DEBOUNCE_MS = 250;

const defaultFs: FileMirrorFsPort = {
  mkdir: (path, options) => mkdir(path, options),
  rename: (from, to) => rename(from, to),
  rm: (path, options) => rm(path, options),
  writeFile: (path, content, encoding) => writeFile(path, content, encoding),
};

const defaultTimers: FileMirrorTimers = {
  clearTimeout: (handle) => clearTimeout(handle as ReturnType<typeof setTimeout>),
  setTimeout: (callback, delayMs) => setTimeout(callback, delayMs),
};

const DURABLE_SCOPE_KEYS = ["userId", "tenantId", "workspaceId", "agentId"] as const;

// The mirror tracks durable memory, so the session refinement is dropped:
// a session-scoped remember still mirrors the durable scope it wrote into.
export function toDurableMirrorScope(scope: MemoryScope): MemoryScope {
  const { sessionId: _sessionId, ...durable } = scope;
  return durable;
}

// A mutation belongs to the mirror when every field the bound scope fixes
// matches. Fields the bound scope leaves unset admit any value, so a
// workspace-bound mirror is regenerated by every agent writing into it.
export function isWithinMirrorScope(bound: MemoryScope, scope: MemoryScope): boolean {
  const anchor = normalizeScope(bound);
  const target = normalizeScope(scope);
  return DURABLE_SCOPE_KEYS.every(
    (key) => anchor[key] === undefined || anchor[key] === target[key],
  );
}

function boundMirrorScope(scope: MemoryScope): MemoryScope {
  const normalized = normalizeScope(scope);
  const bound: MemoryScope = { userId: normalized.userId };
  for (const key of DURABLE_SCOPE_KEYS) {
    if (key !== "userId" && normalized[key] !== undefined) {
      bound[key] = normalized[key];
    }
  }
  return bound;
}

function isMissingPathError(error: unknown): boolean {
  return Boolean(error) && typeof error === "object" && (error as { code?: unknown }).code === "ENOENT";
}

export function createFileMirror(deps: FileMirrorDeps): FileMirror {
  const fs = deps.fs ?? defaultFs;
  const timers = deps.timers ?? defaultTimers;
  const now = deps.now ?? (() => new Date());
  const debounceMs = Math.max(0, deps.config.debounceMs ?? FILE_MIRROR_DEFAULT_DEBOUNCE_MS);
  const root = deps.config.root;
  const scope = boundMirrorScope(deps.config.scope);
  let sequence = 0;
  let timer: unknown = null;
  let inFlight: Promise<void> | null = null;
  let dirty = false;

  const swapIn = async (stagingRoot: string, retiredRoot: string): Promise<void> => {
    let retired = false;
    try {
      await fs.rename(root, retiredRoot);
      retired = true;
    } catch (error) {
      if (!isMissingPathError(error)) {
        throw error;
      }
    }
    try {
      await fs.rename(stagingRoot, root);
    } catch (error) {
      if (retired) {
        // Put the previous tree back so a failed swap never leaves the root
        // missing; the staging tree is removed by the caller.
        await fs.rename(retiredRoot, root).catch(() => undefined);
      }
      throw error;
    }
    if (retired) {
      await fs.rm(retiredRoot, { force: true, recursive: true });
    }
  };

  const writeBundle = async (exported: FileMirrorExport): Promise<number> => {
    sequence += 1;
    const swapId = `${now().getTime().toString(36)}-${sequence}`;
    const stagingRoot = `${root}.tmp-${swapId}`;
    const files = [...exported.artifacts.files, ...exported.pages.files];
    await fs.mkdir(stagingRoot, { recursive: true });
    try {
      for (const file of files) {
        const destination = join(stagingRoot, file.relativePath);
        await fs.mkdir(dirname(destination), { recursive: true });
        await fs.writeFile(destination, file.content, "utf8");
      }
      await swapIn(stagingRoot, `${root}.old-${swapId}`);
    } catch (error) {
      await fs.rm(stagingRoot, { force: true, recursive: true }).catch(() => undefined);
      throw error;
    }
    return files.length;
  };

  const regenerate = async (): Promise<void> => {
    const trace = deps.tracer
      ? await deps.tracer.start({
          name: "governance.file_mirror",
          scope,
          attributes: { root },
        })
      : null;
    try {
      const fileCount = await writeBundle(
        await deps.exportMemory({ includeRuntime: false, scope }),
      );
      await trace?.succeeded({ attributes: { fileCount } });
    } catch (error) {
      await trace?.failed({ error });
      deps.onFailure?.(error, scope);
    }
  };

  const run = (): Promise<void> => {
    if (timer !== null) {
      timers.clearTimeout(timer);
      timer = null;
    }
    if (inFlight) {
      dirty = true;
      return inFlight;
    }
    dirty = false;
    inFlight = regenerate().then(async () => {
      inFlight = null;
      if (dirty) {
        await run();
      }
    });
    return inFlight;
  };

  return {
    root,
    schedule(mutated) {
      if (!isWithinMirrorScope(scope, mutated)) {
        return;
      }
      if (timer !== null) {
        timers.clearTimeout(timer);
      }
      timer = timers.setTimeout(() => {
        timer = null;
        void run();
      }, debounceMs);
    },
    async flush() {
      // Drain until no timer is pending and no write is in flight. An
      // in-flight write is awaited as-is (it reruns itself when dirty); only
      // a timer-pending regeneration is started early.
      while (timer !== null || inFlight) {
        await (inFlight ?? run());
      }
    },
  };
}
