export const ROOT_HELP_TEXT = [
  "GoodMemory CLI",
  "",
  "Usage",
  "  goodmemory <command> [options]",
  "",
  "Commands",
  "  adopt           Detect this environment and print the right onboarding path",
  "  setup           Configure GoodMemory memory enhancement for installed hosts",
  "  remember        Write durable memory through the public API",
  "  feedback        Write explicit feedback or correction through the public API",
  "  forget          Delete one durable memory record or clear a scoped target",
  "  inspect         Inspect scope-bounded memory from durable storage",
  "  trace           Run read-only recall diagnostics for a scope and query",
  "  export-memory   Export a memory snapshot plus Markdown artifacts",
  "  import-memory   Import memory pages or a snapshot export into a scope",
  "  stats           Show scope-bounded counts and storage metadata",
  "  status          Show installed host memory enhancement status",
  "  doctor          Diagnose installed host wiring without changing files",
  "  install         Install managed global GoodMemory host config for Codex or Claude Code",
  "  uninstall       Remove managed global GoodMemory host config for Codex or Claude Code",
  "  enable          Enable repo-local GoodMemory host opt-in for Codex or Claude Code",
  "  disable         Disable repo-local GoodMemory host opt-in for Codex or Claude Code",
  "  repair          Repair missing managed installed-host wiring",
  "  mcp             Run the installed GoodMemory MCP server",
  "  storage         Run explicit storage maintenance commands",
  "  runtime         Run optional local runtime tools such as worker inspection",
  "  inspector       Run the local GoodMemory Inspector admin surface",
  "  codex           Codex bootstrap and installed hook commands",
  "  claude          Claude Code bootstrap and installed hook commands",
  "  eval            Inspect eval run artifacts",
  "",
  "Help",
  "  goodmemory --help",
  "  goodmemory <command> --help",
  "  goodmemory setup --help",
  "  goodmemory status --help",
  "  goodmemory doctor --help",
  "  goodmemory eval --help",
  "  goodmemory install --help",
  "  goodmemory enable --help",
  "  goodmemory repair --help",
  "  goodmemory mcp --help",
  "  goodmemory storage --help",
  "  goodmemory runtime --help",
  "  goodmemory inspector --help",
  "  goodmemory codex --help",
  "  goodmemory claude --help",
  "  goodmemory --schema       Print the CLI surface (commands and flags) as JSON",
  "  goodmemory -V, --version",
].join("\n");
export const SETUP_HELP_TEXT = [
  "GoodMemory Setup CLI",
  "",
  "Usage",
  "  goodmemory setup [options]",
  "",
  "Options",
  "  --host <codex|claude|both>  Optional, defaults to detected installed hosts",
  "  --user-id <id>              Optional, defaults to the current OS username",
  "  --activation-mode <global|workspace_opt_in>",
  "  --context-mode <fragment|progressive>",
  "  --default-locale <locale>    BCP-47 locale for session-start recall",
  "  --writeback <off|observe|review|selective>",
  "  --file-mirror               Mirror the export bundle to <workspace>/.goodmemory/memory after each write",
  "  --dry-run",
  "  --interactive",
  "  --no-interactive",
  "  --json",
].join("\n");
export const ADOPT_HELP_TEXT = [
  "GoodMemory Adopt CLI",
  "",
  "Detect this environment (Codex/Claude CLI, .codex/ and .claude/ config,",
  "existing MCP wiring) and print the recommended onboarding path plus the",
  "exact next command. Read-only: it changes nothing, it only advises.",
  "",
  "Usage",
  "  goodmemory adopt [options]",
  "",
  "Options",
  "  --host <codex|claude>  Force a host instead of auto-detecting",
  "  --json                 Emit a machine-readable onboarding plan",
].join("\n");
export const DOCTOR_HELP_TEXT = [
  "GoodMemory Doctor CLI",
  "",
  "Usage",
  "  goodmemory doctor [codex|claude|both] [options]",
  "",
  "Options",
  "  --workspace-root <path>   Optional, defaults to the current working directory",
  "  --json",
  "",
  "Doctor is read-only. It reports installed host config, hook, MCP, context,",
  "writeback, workspace, and repair hints without creating runtime storage.",
].join("\n");
export const EVAL_HELP_TEXT = [
  "GoodMemory Eval CLI",
  "",
  "Usage",
  "  goodmemory eval <command> [options]",
  "",
  "Commands",
  "  inspect       Summarize one eval case from a run directory",
  "  trace         Render recall/write/assertion traces for one eval case",
  "  export-case   Copy one eval case artifact to a target path",
  "",
  "Help",
  "  goodmemory eval --help",
  "  goodmemory eval <command> --help",
].join("\n");
export const INSPECT_HELP_TEXT = [
  "GoodMemory Inspect",
  "",
  "Usage",
  "  goodmemory inspect --user-id <id> [scope flags] [storage flags] [output flags]",
  "",
  "Scope Flags",
  "  --user-id <id>          Required",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "  --session-id <id>",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "",
  "Output Flags",
  "  --include-runtime",
  "  --json",
].join("\n");
export const TRACE_HELP_TEXT = [
  "GoodMemory Trace",
  "",
  "Usage",
  "  goodmemory trace --user-id <id> --query <text> [scope flags] [diagnostic flags] [storage flags]",
  "",
  "Scope Flags",
  "  --user-id <id>          Required",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "  --session-id <id>",
  "",
  "Diagnostic Flags",
  "  --query <text>          Required",
  "  --retrieval-profile <general_chat|coding_agent>",
  "  --strategy <auto|rules-only|hybrid|llm-assisted>",
  "  --locale <locale>",
  "  --reference-time <rfc3339>",
  "  --timezone <iana-zone>",
  "  --ignore-memory         Treat recall as an empty set and skip storage lookup",
  "  --json",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
].join("\n");
export const EXPORT_MEMORY_HELP_TEXT = [
  "GoodMemory Export Memory",
  "",
  "Usage",
  "  goodmemory export-memory --user-id <id> --output <path> [scope flags] [storage flags] [options]",
  "",
  "Scope Flags",
  "  --user-id <id>          Required",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "  --session-id <id>",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "",
  "Options",
  "  --output <path>         Required",
  "  --include-runtime",
  "  --force",
].join("\n");
export const IMPORT_MEMORY_HELP_TEXT = [
  "GoodMemory Import Memory",
  "",
  "Usage",
  "  goodmemory import-memory --user-id <id> --input <path> [scope flags] [storage flags] [options]",
  "",
  "Input",
  "  --input <path>          Required. A pages directory (flat *.md or a pages/ child),",
  "                          one .md page, or a memory-export.json snapshot",
  "",
  "Scope Flags",
  "  --user-id <id>          Required",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "",
  "Options",
  "  --dry-run               Report outcomes and the input sha256 without writing",
  "  --yes                   Confirm the write without pinning the input hash",
  "  --expect-sha256 <hex>   Confirm the write only if the input hashes to this value",
  "  --oversize <reject|split>  Pages over the 8192-byte note cap (default: reject)",
  "  --locale <bcp47>",
  "  --json",
  "",
  "Writes require --yes or --expect-sha256. Pages become note memories; a",
  "snapshot restores durable records by id and skips unchanged ones.",
].join("\n");
export const STATS_HELP_TEXT = [
  "GoodMemory Stats",
  "",
  "Usage",
  "  goodmemory stats --user-id <id> [scope flags] [storage flags] [output flags]",
  "",
  "Scope Flags",
  "  --user-id <id>          Required",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "  --session-id <id>",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "",
  "Output Flags",
  "  --include-runtime",
  "  --json",
].join("\n");
export const INSTALL_HELP_TEXT = [
  "GoodMemory Install CLI",
  "",
  "Usage",
  "  goodmemory install <codex|claude> [options]",
  "",
  "Commands",
  "  codex         Install managed global GoodMemory host config for Codex",
  "  claude        Install managed global GoodMemory host config for Claude Code",
  "",
  "Options",
  "  --user-id <id>            Optional, defaults to the current OS username",
  "  --memory-path <path>      SQLite shortcut. Defaults to ~/.goodmemory/memory.sqlite",
  "  --storage-provider <sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "  --embedding-provider <openai>",
  "  --embedding-model <model>",
  "  --embedding-api-key <key>",
  "  --embedding-base-url <url>",
  "  --llm-provider <openai|anthropic>",
  "  --llm-model <model>",
  "  --llm-api-key <key>",
  "  --llm-base-url <url>",
  "  --activation-mode <global|workspace_opt_in>",
  "  --default-locale <locale>  BCP-47 locale for session-start recall",
  "  --writeback <off|observe|review|selective>",
  "  --file-mirror             Mirror the export bundle to <workspace>/.goodmemory/memory after each write",
  "  --dry-run",
  "  --interactive",
  "  --no-interactive",
  "  --json",
  "",
  "Interactive terminals prompt for missing storage/provider settings unless --no-interactive or --json is used; --interactive forces prompts.",
  "If provider setup is skipped, install still succeeds in local rules-only mode.",
  "Add them later by rerunning install with flags or editing ~/.goodmemory/<host>.json.",
].join("\n");
export const UNINSTALL_HELP_TEXT = [
  "GoodMemory Uninstall CLI",
  "",
  "Usage",
  "  goodmemory uninstall <codex|claude> [--json]",
].join("\n");
export const STATUS_HELP_TEXT = [
  "GoodMemory Status CLI",
  "",
  "Usage",
  "  goodmemory status [codex|claude] [options]",
  "",
  "Options",
  "  --workspace-root <path>   Optional, defaults to the current working directory",
  "  --json",
].join("\n");
export const ENABLE_HELP_TEXT = [
  "GoodMemory Enable CLI",
  "",
  "Usage",
  "  goodmemory enable <codex|claude> [options]",
  "",
  "Options",
  "  --workspace-id <id>       Optional, defaults to the workspace folder name",
  "  --workspace-root <path>   Optional, defaults to the current working directory",
  "  --context-mode <fragment|progressive>",
  "  --writeback <off|observe|review|selective>",
  "  --dry-run",
  "  --json",
].join("\n");
export const REPAIR_HELP_TEXT = [
  "GoodMemory Repair CLI",
  "",
  "Usage",
  "  goodmemory repair [codex|claude|both] [options]",
  "",
  "Options",
  "  --workspace-root <path>   Optional, defaults to the current working directory",
  "  --dry-run",
  "  --json",
  "",
  "Repair only rewrites GoodMemory-managed host wiring or absent managed targets.",
  "It preserves existing installed config, context mode, providers, storage, and",
  "writeback mode.",
].join("\n");
export const DISABLE_HELP_TEXT = [
  "GoodMemory Disable CLI",
  "",
  "Usage",
  "  goodmemory disable <codex|claude> [options]",
  "",
  "Options",
  "  --workspace-root <path>   Optional, defaults to the current working directory",
  "  --json",
].join("\n");
export const REMEMBER_HELP_TEXT = [
  "GoodMemory Remember",
  "",
  "Usage",
  "  goodmemory remember --message <text> [scope flags] [write flags] [storage flags] [installed-host flags]",
  "",
  "Scope Flags",
  "  --user-id <id>          Required unless --host derives it from installed host config",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "  --session-id <id>",
  "",
  "Write Flags",
  "  --message <text>        Required",
  "  --role <user|assistant>",
  "  --kind note             Store the message verbatim as an authored note page (requires --title)",
  "  --title <text>          Note title; the identity key for supersession (with --kind note)",
  "  --tags <a,b>            Optional comma-separated note tags (with --kind note)",
  "  --extraction-strategy <auto|rules-only|llm-assisted>",
  "  --locale <locale>",
  "  --observed-at <rfc3339>",
  "  --timezone <iana-zone>",
  "",
  "Installed Host Flags",
  "  --host <codex|claude>   Reuse installed host storage and derive missing scope defaults",
  "  --workspace-root <path> Optional, defaults to the current working directory when --host is set",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "",
  "Output Flags",
  "  --json",
].join("\n");
export const FEEDBACK_HELP_TEXT = [
  "GoodMemory Feedback",
  "",
  "Usage",
  "  goodmemory feedback --signal <text> [scope flags] [storage flags] [installed-host flags]",
  "",
  "Scope Flags",
  "  --user-id <id>          Required unless --host derives it from installed host config",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "  --session-id <id>",
  "",
  "Feedback Flags",
  "  --signal <text>         Required",
  "  --locale <locale>",
  "",
  "Installed Host Flags",
  "  --host <codex|claude>   Reuse installed host storage and derive missing scope defaults",
  "  --workspace-root <path> Optional, defaults to the current working directory when --host is set",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "",
  "Output Flags",
  "  --json",
].join("\n");
export const FORGET_HELP_TEXT = [
  "GoodMemory Forget",
  "",
  "Usage",
  "  goodmemory forget --memory-id <id> [scope flags] [storage flags] [installed-host flags]",
  "  goodmemory forget --all [scope flags] [storage flags] [installed-host flags] [--include-runtime]",
  "",
  "Scope Flags",
  "  --user-id <id>          Required unless --host derives it from installed host config",
  "  --tenant-id <id>",
  "  --workspace-id <id>",
  "  --agent-id <id>",
  "  --session-id <id>",
  "",
  "Forget Flags",
  "  --memory-id <id>        Delete one durable memory record. Use either this or --all",
  "  --all                  Delete the full durable scope. Use either this or --memory-id",
  "  --include-runtime      Include working memory, journal, and artifact spills when used with --all",
  "",
  "Installed Host Flags",
  "  --host <codex|claude>   Reuse installed host storage and derive missing scope defaults",
  "  --workspace-root <path> Optional, defaults to the current working directory when --host is set",
  "",
  "Storage Flags",
  "  --storage-provider <memory|sqlite|postgres>",
  "  --storage-url <path-or-url>",
  "",
  "Output Flags",
  "  --json",
].join("\n");
export const MCP_HELP_TEXT = [
  "GoodMemory MCP CLI",
  "",
  "Usage",
  "  goodmemory mcp <command> [options]",
  "",
  "Commands",
  "  serve         Run the installed GoodMemory MCP server over stdio",
  "",
  "Help",
  "  goodmemory mcp --help",
  "  goodmemory mcp serve --help",
].join("\n");
export const STORAGE_HELP_TEXT = [
  "GoodMemory Storage CLI",
  "",
  "Usage",
  "  goodmemory storage <command> [options]",
  "",
  "Commands",
  "  migrate       Build Postgres document indexes at deployment time",
  "",
  "Help",
  "  goodmemory storage --help",
  "  goodmemory storage migrate --help",
].join("\n");
export const STORAGE_MIGRATE_HELP_TEXT = [
  "GoodMemory Postgres Document Index Migration",
  "",
  "Usage",
  "  goodmemory storage migrate --storage-provider postgres --storage-url <url> [options]",
  "",
  "Required",
  "  --storage-provider postgres",
  "  --storage-url <url>",
  "",
  "Options",
  "  --storage-schema <schema>  Defaults to public",
  "  --json",
  "",
  "This builds document indexes outside request startup; it does not migrate session or vector storage.",
].join("\n");
export const MCP_SERVE_HELP_TEXT = [
  "GoodMemory MCP Serve",
  "",
  "Usage",
  "  goodmemory mcp serve --host <codex|claude>",
  "  goodmemory mcp serve --standalone --user-id <id> [--workspace-id <id>] [--agent-id <id>]",
  "                       [--storage-provider <memory|sqlite|postgres>] [--storage-url <path-or-url>]",
  "                       [--max-tokens <n>] [--retrieval-profile <coding_agent|general_chat>]",
  "                       [--allow-write]",
  "",
  "Standalone mode runs without installed host config; any MCP client can use it.",
  "Flag fallbacks: GOODMEMORY_USER_ID, GOODMEMORY_WORKSPACE_ID, GOODMEMORY_AGENT_ID,",
  "GOODMEMORY_STORAGE_PROVIDER, GOODMEMORY_STORAGE_URL, GOODMEMORY_MCP_ALLOW_WRITE.",
  "Scope note: --agent-id hard-filters recall to that agent's records; omit it to",
  "see agent-less records (installed-host memories stay agent-private unless named).",
  "--allow-write (or GOODMEMORY_MCP_ALLOW_WRITE=1) registers the opt-in",
  "goodmemory_remember write tool; the default surface is read-only.",
].join("\n");
export const RUNTIME_HELP_TEXT = [
  "GoodMemory Runtime CLI",
  "",
  "Usage",
  "  goodmemory runtime <command> [options]",
  "",
  "Commands",
  "  worker       Inspect and drain the optional local runtime worker queue",
  "  viewer       Run the optional read-only local memory viewer",
  "",
  "Help",
  "  goodmemory runtime --help",
  "  goodmemory runtime worker --help",
  "  goodmemory runtime viewer --help",
].join("\n");
export const RUNTIME_WORKER_HELP_TEXT = [
  "GoodMemory Runtime Worker",
  "",
  "Usage",
  "  goodmemory runtime worker status [--queue-file <path>] [--json]",
  "  goodmemory runtime worker drain-once [--queue-file <path>] [--max-jobs <n>] [--json]",
  "  goodmemory runtime worker recover --dry-run [--queue-file <path>] [--json]",
  "  goodmemory runtime worker start [--queue-file <path>] [--json]",
  "  goodmemory runtime worker stop [--queue-file <path>] [--json]",
  "",
  "Worker commands are optional local inspection tools. They do not make daemon",
  "mode required and do not persist raw transcripts.",
].join("\n");
export const RUNTIME_VIEWER_HELP_TEXT = [
  "GoodMemory Runtime Viewer",
  "",
  "Usage",
  "  goodmemory runtime viewer --host <codex|claude> --port <n> [--token <secret>]",
  "  goodmemory runtime viewer --host <codex|claude> --dry-run [--json]",
  "",
  "Deprecated: delegates to the scope-bound read-only Inspector.",
  "",
  "Viewer security",
  "  binds 127.0.0.1 only",
  "  requires a local token",
  "  read-only API; no mutation routes and no CORS",
  "  static local shell; no raw transcript display",
].join("\n");
export const INSPECTOR_HELP_TEXT = [
  "GoodMemory Inspector",
  "",
  "Usage",
  "  goodmemory inspector serve [--port <n>] [--token <secret>] [--storage-url <path>]",
  "  goodmemory inspector serve --dry-run [--json]",
  "",
  "The Inspector is a local admin surface: browse memory across scopes, review",
  "writeback candidates, debug recall, and forget/revise/delete a scope's memory.",
  "",
  "Security",
  "  binds 127.0.0.1 only",
  "  requires a local token; every mutation needs Authorization: Bearer",
  "  read-only reads, gated writes; every mutation is audit-logged; no CORS",
  "  no raw transcript display",
  "  --user-id is optional; scope discovery is the point",
].join("\n");
export const EVAL_INSPECT_HELP_TEXT = [
  "GoodMemory Eval Inspect",
  "",
  "Usage",
  "  goodmemory eval inspect --run-dir <path> --case-id <id> [--json]",
].join("\n");
export const EVAL_TRACE_HELP_TEXT = [
  "GoodMemory Eval Trace",
  "",
  "Usage",
  "  goodmemory eval trace --run-dir <path> --case-id <id> [--json]",
].join("\n");
export const EVAL_EXPORT_CASE_HELP_TEXT = [
  "GoodMemory Eval Export Case",
  "",
  "Usage",
  "  goodmemory eval export-case --run-dir <path> --case-id <id> --output <path> [--force] [--json]",
].join("\n");
export const CODEX_HELP_TEXT = [
  "GoodMemory Codex CLI",
  "",
  "Usage",
  "  goodmemory codex <command> [options]",
  "",
  "Commands",
  "  action        Run the installed Codex action bridge with pre-action assessment",
  "  bootstrap     Generate repo-local Codex wiring on the installed package surface",
  "  hook          Run installed Codex hook handlers from stdin JSON",
  "  writeback     Run opt-in installed Codex selective writeback from stdin JSON",
  "",
  "Help",
  "  goodmemory codex --help",
  "  goodmemory codex action --help",
  "  goodmemory codex bootstrap --help",
  "  goodmemory codex hook --help",
  "  goodmemory codex writeback --help",
].join("\n");
export const CODEX_ACTION_HELP_TEXT = [
  "GoodMemory Codex Action",
  "",
  "Usage",
  "  goodmemory codex action --session-id <id> --command <command> [--run-id <id>] [--attempt-id <id>] [--action-id <id>] [--turn-id <id>] [--sequence <n>] [--json]",
  "",
  "Executes the installed Codex action bridge: assessAction(), rewrite/veto, first-step execution, and lineage/evidence recording in installed storage.",
].join("\n");
export const CLAUDE_HELP_TEXT = [
  "GoodMemory Claude CLI",
  "",
  "Usage",
  "  goodmemory claude <command> [options]",
  "",
  "Commands",
  "  bootstrap     Generate repo-local Claude Code wiring on the installed package surface",
  "  hook          Run installed Claude Code hook handlers from stdin JSON",
  "  writeback     Run opt-in installed Claude Code selective writeback from stdin JSON",
  "",
  "Help",
  "  goodmemory claude --help",
  "  goodmemory claude bootstrap --help",
  "  goodmemory claude hook --help",
  "  goodmemory claude writeback --help",
].join("\n");
export const CODEX_BOOTSTRAP_HELP_TEXT = [
  "GoodMemory Codex Bootstrap",
  "",
  "Usage",
  "  goodmemory codex bootstrap --user-id <id> [--workspace-id <id>] [--workspace-root <path>] [--json]",
].join("\n");
export const CLAUDE_BOOTSTRAP_HELP_TEXT = [
  "GoodMemory Claude Bootstrap",
  "",
  "Usage",
  "  goodmemory claude bootstrap --user-id <id> [--workspace-id <id>] [--workspace-root <path>] [--json]",
].join("\n");
export const CODEX_HOOK_HELP_TEXT = [
  "GoodMemory Codex Hook",
  "",
  "Usage",
  "  goodmemory codex hook <pre-tool-use|session-start|session-stop|user-prompt-submit>",
  "",
  "Commands",
  "  pre-tool-use        Read Codex PreToolUse Bash JSON from stdin and deny/redirect risky commands",
  "  session-start        Read Codex SessionStart JSON from stdin and emit additionalContext JSON",
  "  session-stop         Read Codex Stop JSON from stdin and learn bounded session signals",
  "  user-prompt-submit   Read Codex UserPromptSubmit JSON from stdin and emit additionalContext JSON",
].join("\n");
export const CODEX_WRITEBACK_HELP_TEXT = [
  "GoodMemory Codex Writeback",
  "",
  "Usage",
  "  goodmemory codex writeback [--mode off|observe|review|selective] [--dry-run] [--json]",
  "  goodmemory codex writeback --from-rollout [--rollout-path <path>] [--sessions-root <path>] [--workspace-root <path>] [--json]",
  "  goodmemory codex writeback inspect [--limit <n>] [--json]",
  "  goodmemory codex writeback forget --event-id <id> [--review-outcome <valid_write|false_write|uncertain>] [--review-reason <text>] [--json]",
  "",
  "Rollout capture",
  "  --from-rollout          Read a Codex rollout JSONL instead of hook JSON from stdin",
  "  --rollout-path <path>   Read one explicit rollout file",
  "  --sessions-root <path>  Search this Codex sessions root for the latest rollout",
  "  --workspace-root <path> Scope latest-rollout search to this workspace",
  "",
  "Modes",
  "  off        recall-only; no after-response candidate extraction",
  "  observe    stores local bounded/redacted candidate previews for review; no raw transcripts or durable memory writes",
  "  review     queues bounded/redacted candidates for Inspector approval; no durable write until approved",
  "  selective  writes selected candidates through public remember()",
  "",
  "Reads native Codex Stop hook JSON from stdin. --from-rollout is an explicit compatibility and diagnostic fallback.",
  "Inspect lists recent audit events. Forget deletes linked durable records, or dismisses observe-only events.",
].join("\n");
export const CLAUDE_HOOK_HELP_TEXT = [
  "GoodMemory Claude Hook",
  "",
  "Usage",
  "  goodmemory claude hook <session-start|session-stop|user-prompt-submit>",
  "",
  "Commands",
  "  session-start        Read Claude SessionStart JSON from stdin and emit additionalContext JSON",
  "  session-stop         Read Claude Stop JSON from stdin and learn bounded session signals",
  "  user-prompt-submit   Read Claude UserPromptSubmit JSON from stdin and emit additionalContext JSON",
].join("\n");
export const CLAUDE_WRITEBACK_HELP_TEXT = [
  "GoodMemory Claude Writeback",
  "",
  "Usage",
  "  goodmemory claude writeback [--mode off|observe|review|selective] [--dry-run] [--json]",
  "  goodmemory claude writeback inspect [--limit <n>] [--json]",
  "  goodmemory claude writeback forget --event-id <id> [--review-outcome <valid_write|false_write|uncertain>] [--review-reason <text>] [--json]",
  "",
  "Modes",
  "  off        recall-only; no after-response candidate extraction",
  "  observe    stores local bounded/redacted candidate previews for review; no raw transcripts or durable memory writes",
  "  review     queues bounded/redacted candidates for Inspector approval; no durable write until approved",
  "  selective  writes selected candidates through public remember()",
  "",
  "Reads Claude after-response/session-end JSON from stdin and runs installed-host writeback.",
  "Inspect lists recent audit events. Forget deletes linked durable records, or dismisses observe-only events.",
].join("\n");
