import { readFileSync } from "node:fs";

// Machine-readable capability descriptor for autonomous agents that discover
// GoodMemory (e.g. scanning GitHub or hitting a deployed bridge) and want to
// decide, without reading prose, whether and how to give themselves memory.
//
// This module is the single source of truth. Two consumers derive from it:
//   1. The static `.well-known/goodmemory.json` (regenerated by
//      `scripts/generate-capability-descriptor.ts`, golden-checked in tests)
//      that repo scanners fetch straight from the tree.
//   2. The running HTTP bridge, which serves it at
//      `GET /.well-known/goodmemory.json` for agents that reach a deployment.
// Keeping both on one builder means they cannot drift.

const PACKAGE_JSON_URL = new URL("../../package.json", import.meta.url);
export const BENCHMARK_EVIDENCE_BOUNDARY_NOTE =
  "No end-to-end benchmark runner is currently allowlisted for claim promotion. " +
  "The retained v0.7.3 LoCoMo and v0.6.0 LoCoMo, BEAM, and MemoryAgentBench " +
  "measurements, plus ImplicitMemBench, are internal diagnostics only. LongMemEval " +
  "is withdrawn and paused pending a clean label-free rerun. Current and historical " +
  "promotion both fail closed; stored-answer rescores and legacy projections cannot " +
  "open the boundary. None is versioned evidence or a current package claim.";

export interface GoodMemoryPackageReleaseMetadata {
  readonly installCommandsApplyAfterPublish: boolean;
  readonly npmDistTag: string;
  readonly status: "release-candidate" | "stable";
}

export interface GoodMemoryCapabilityPackageMetadata {
  readonly goodmemoryRelease: GoodMemoryPackageReleaseMetadata;
  readonly version: string;
}

let packageMetadataCache: GoodMemoryCapabilityPackageMetadata | undefined;

function readPackageMetadata(): GoodMemoryCapabilityPackageMetadata {
  if (packageMetadataCache) {
    return packageMetadataCache;
  }

  const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_URL, "utf8")) as {
    goodmemoryRelease?: Partial<GoodMemoryPackageReleaseMetadata>;
    version?: unknown;
  };
  const release = packageJson.goodmemoryRelease;
  if (
    typeof packageJson.version !== "string" ||
    packageJson.version.length === 0 ||
    typeof release?.installCommandsApplyAfterPublish !== "boolean" ||
    typeof release.npmDistTag !== "string" ||
    release.npmDistTag.length === 0 ||
    (release.status !== "release-candidate" && release.status !== "stable")
  ) {
    throw new Error("Unable to read GoodMemory package release metadata.");
  }

  packageMetadataCache = {
    goodmemoryRelease: {
      installCommandsApplyAfterPublish: release.installCommandsApplyAfterPublish,
      npmDistTag: release.npmDistTag,
      status: release.status,
    },
    version: packageJson.version,
  };
  return packageMetadataCache;
}

export interface GoodMemoryCapabilityOnboardingPath {
  readonly audience: string;
  readonly when: string;
  readonly method: "cli" | "mcp" | "http" | "plugin";
  readonly install?: string;
  readonly runtimeRequirements?: readonly string[];
  readonly writeBoundary?: string;
  readonly steps?: readonly string[];
  readonly mcpServer?: {
    readonly command: string;
    readonly args: readonly string[];
  };
  readonly endpoint?: string;
  readonly selfHost?: string;
  readonly pythonClient?: string;
  readonly autoDetect?: string;
  readonly docs: string;
}

export interface GoodMemoryCapabilityBenchmarkClaim {
  readonly name: string;
  readonly config: string;
  readonly metric: string;
  readonly result: string;
  readonly reference: string;
  readonly claimDeclaration: string;
  readonly runtimeProfile: string;
  readonly measuredPackageVersion: string;
}

export interface GoodMemoryCapabilityDescriptor {
  readonly schemaVersion: string;
  readonly name: string;
  readonly version: string;
  readonly kind: "memory-layer";
  readonly summary: string;
  readonly description: string;
  readonly notA: readonly string[];
  readonly license: string;
  readonly homepage: string;
  readonly repository: string;
  readonly documentation: {
    readonly inspector: string;
    readonly llmsTxt: string;
    readonly readme: string;
    readonly quickstart: string;
  };
  readonly install: {
    readonly npmGlobal: string;
    readonly npmPackage: string;
    readonly bun: string;
  };
  readonly releaseStatus: {
    readonly installCommandsApplyAfterPublish: boolean;
    readonly npmDistTag: string;
    readonly status: "release-candidate" | "stable";
    readonly tarball: string;
  };
  readonly memoryApi: readonly string[];
  readonly onboarding: readonly GoodMemoryCapabilityOnboardingPath[];
  readonly mcp: {
    readonly command: string;
    readonly standaloneArgs: readonly string[];
    readonly primaryTools: readonly string[];
    readonly readOnlyToolCount: number;
    readonly writeTool: string;
    readonly noteTool: string;
    readonly registryName: string;
    readonly docs: string;
  };
  readonly http: {
    readonly hosted: string;
    readonly liveness: string;
    readonly wellKnown: string;
    readonly auth: string;
    readonly selfHost: string;
    readonly endpoints: Readonly<Record<string, string>>;
    readonly pythonClient: string;
    readonly docs: string;
  };
  readonly benchmarks: {
    readonly currentClaims: readonly GoodMemoryCapabilityBenchmarkClaim[];
    readonly historicalEvidence: {
      readonly url: string;
      readonly note: string;
    };
  };
  readonly capabilities: {
    readonly localFirst: boolean;
    readonly embeddingFreeDefault: boolean;
    readonly builtInLanguagePacks: readonly string[];
    readonly durableStore: string;
    readonly audit: boolean;
    readonly deletion: boolean;
    readonly localInspector: string;
    readonly correctByDefaultRecall: string;
  };
  readonly canonicalSources: {
    readonly prose: string;
    readonly benchmarks: string;
    readonly note: string;
  };
}

const REPO = "https://github.com/hjqcan/GoodMemory";
const HOSTED = "https://goodmemory.vibenest.net";

/**
 * Build the GoodMemory capability descriptor. `options.version` overrides the
 * package.json lookup so tests stay deterministic without filesystem access.
 */
export function buildGoodMemoryCapabilityDescriptor(
  options: {
    packageMetadata?: GoodMemoryCapabilityPackageMetadata;
    version?: string;
  } = {},
): GoodMemoryCapabilityDescriptor {
  const packageMetadata = options.packageMetadata ?? readPackageMetadata();
  const version = options.version ?? packageMetadata.version;
  const currentClaims: GoodMemoryCapabilityBenchmarkClaim[] = [];

  return {
    schemaVersion: "goodmemory.capability/v2",
    name: "goodmemory",
    version,
    kind: "memory-layer",
    summary:
      "Durable user/project memory layer for chat apps, copilots, and coding agents.",
    description:
      "GoodMemory is the product memory layer between an app or installed agent host and the model runtime: write selected facts, recall the right context, inject it into the next turn, audit what happened, and delete it when it is wrong.",
    notA: ["llm", "agent-framework", "vector-database", "rag-system"],
    license: "MIT",
    homepage: `${REPO}#readme`,
    repository: REPO,
    documentation: {
      inspector: `${REPO}/blob/main/docs/GoodMemory-Inspector-and-Admin-API.md`,
      llmsTxt: `${REPO}/blob/main/llms.txt`,
      readme: `${REPO}#readme`,
      quickstart: `${REPO}#quickstart-codex-or-claude-code-memory`,
    },
    install: {
      npmGlobal: `npm install -g goodmemory@${version}`,
      npmPackage: `npm install goodmemory@${version}`,
      bun: `bun add goodmemory@${version}`,
    },
    releaseStatus: {
      ...packageMetadata.goodmemoryRelease,
      tarball: `goodmemory-${version}.tgz`,
    },
    memoryApi: [
      "remember",
      "recall",
      "buildContext",
      "feedback",
      "forget",
      "exportMemory",
      "deleteAllMemory",
    ],
    onboarding: [
      {
        audience: "installed-coding-agent-host",
        when: "You are, or run inside, Claude Code or Codex.",
        method: "cli",
        steps: [
          `npm install -g goodmemory@${version}`,
          "goodmemory setup",
          "goodmemory status",
        ],
        autoDetect: "goodmemory adopt",
        docs: `${REPO}#quickstart-codex-or-claude-code-memory`,
      },
      {
        audience: "kimi-code-plugin",
        when: "You run Kimi Code and want local, scoped cross-session project memory.",
        method: "plugin",
        install: `/plugins install ${REPO}`,
        runtimeRequirements: ["Node.js >=20", "Bun >=1.3.14", "npx"],
        writeBoundary:
          "goodmemory_remember is exposed at install; Kimi Code approval still governs each unapproved MCP call",
        docs: `${REPO}/blob/main/docs/GoodMemory-Kimi-Code-Setup-Guide.md`,
      },
      {
        audience: "mcp-client",
        when: "You speak the Model Context Protocol (Cursor, Windsurf, Cline, Claude Desktop, Gemini CLI, OpenCode, or a custom MCP client).",
        method: "mcp",
        mcpServer: {
          command: "goodmemory-mcp",
          args: ["--standalone", "--user-id", "YOUR_USER_ID"],
        },
        autoDetect: "goodmemory adopt",
        docs: `${REPO}#standalone-mcp-for-any-client`,
      },
      {
        audience: "framework-agent-or-backend",
        when: "You are a framework agent (LangGraph, custom loop) or a backend that calls memory as an HTTP service.",
        method: "http",
        endpoint: HOSTED,
        selfHost:
          "goodmemory-http-bridge --recommended OR GOODMEMORY_PROFILE=agent-recommended goodmemory-http-bridge",
        pythonClient: "pip install goodmemory-client",
        docs: `${REPO}#pythonfastapi-http-bridge`,
      },
    ],
    mcp: {
      command: "goodmemory-mcp",
      standaloneArgs: ["--standalone", "--user-id", "YOUR_USER_ID"],
      primaryTools: ["goodmemory_get_context", "goodmemory_remember"],
      readOnlyToolCount: 8,
      writeTool: "goodmemory_remember (opt-in via --allow-write)",
      noteTool: "goodmemory_write_note (opt-in via --allow-write; verbatim authored pages ≤ 8 KB)",
      registryName: "io.github.hjqcan/goodmemory",
      docs: `${REPO}#standalone-mcp-for-any-client`,
    },
    http: {
      hosted: HOSTED,
      liveness: `${HOSTED}/healthz`,
      wellKnown: `${HOSTED}/.well-known/goodmemory.json`,
      auth: "bearer-token",
      selfHost:
        "goodmemory-http-bridge --recommended OR GOODMEMORY_PROFILE=agent-recommended goodmemory-http-bridge",
      endpoints: {
        recall: "POST /memory/recall-context",
        remember: "POST /memory/remember",
        feedback: "POST /memory/feedback",
        export: "POST /memory/export",
        forget: "POST /memory/forget",
        import: "POST /memory/import",
        revise: "POST /memory/revise",
      },
      pythonClient: "goodmemory-client (PyPI)",
      docs: `${REPO}#pythonfastapi-http-bridge`,
    },
    benchmarks: {
      currentClaims,
      historicalEvidence: {
        url: `${REPO}/tree/main/benchmark-claims`,
        note: BENCHMARK_EVIDENCE_BOUNDARY_NOTE,
      },
    },
    capabilities: {
      localFirst: true,
      embeddingFreeDefault: true,
      builtInLanguagePacks: [
        "en",
        "zh-Hans",
        "zh-Hant",
        "ja",
        "ko",
        "fr",
        "es",
      ],
      durableStore: "sqlite (default), postgres (opt-in)",
      audit: true,
      deletion: true,
      localInspector:
        "goodmemory inspector serve (loopback-only React console and /admin/v1 API)",
      correctByDefaultRecall:
        "Recall never silently degrades: a downgraded strategy carries routing.warnings (semantic_recall_inactive) and routing.warningMessages (semantic recall inactive — set strategy:hybrid + RETRIEVAL_PRESET) instead of quietly returning the lexical floor.",
    },
    canonicalSources: {
      prose: `${REPO}#readme`,
      benchmarks: `${REPO}/tree/main/benchmark-claims`,
      note:
        "Benchmark entries keep explicit measuredPackageVersion provenance; a package version bump never relabels historical results. Source declarations remain in benchmark-claims/*.json.",
    },
  };
}
